### PR TITLE
Switch to prepend instead of alias chaining methods

### LINKED ISSUE #454: Use `prepend` instead of alias method chaining
In multiple places alias method chaining is used instead of prepend. Since cucumber-rails doesn't work with version of Ruby prior to 2.0, these should be updated to the more semantically correct prepend.

### PR DESCRIPTION
**Pull request by wagenet**
Fixes #454

### CODE REVIEW

**Comment by wagenet** [comment]
Looks like the test failures are unrelated.

**Comment by wagenet** [comment]
@luke-hill I can definitely change it. What sort of naming would you prefer?

**Comment by luke-hill** [comment]
your namespacing has an Extensions module. So either add a new folder for that or remove that module.

**Comment by wagenet** [comment]
@luke-hill what about the other stuff in `lib/cucumber/rails/action_controller.rb`? Previously, it had things from two different modules.

**Comment by luke-hill** [comment]
Things aren't great here. So if you want to fix up more stuff, go nuts. I'm just here to make sure we make stuff better ideally with each PR.

**Comment by luke-hill** [comment]
ping @wagenet

**Comment by wagenet** [comment]
@luke-hill sorry for the delay. I think it is ready now. Let me know if you need anything else.

**Comment by wagenet** [comment]
@luke-hill I don't think the CI failures are my fault, but please let me know if I'm mistaken.

File: lib/cucumber/rails/action_dispatch.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+end
+
+module Cucumber
+  module Rails
+    module ActionDispatch
+      module ShowExceptions
+        def call(env)
+          env['action_dispatch.show_detailed_exceptions'] = !ActionController::Base.allow_rescue
+          env['action_dispatch.show_exceptions'] = !env['action_dispatch.show_detailed_exceptions']
+          super
```
Comment (luke-hill) [inline lib/cucumber/rails/action_dispatch.rb]: this should be `super(env)` From previous logic

Comment (wagenet) [reply lib/cucumber/rails/action_dispatch.rb]: Calling `super` without arguments passes all of the original arguments. I'm pretty sure that it will pass the modified `env` object, but given the potential for confusion here, I'll update it.

**Comment by wagenet** [comment]
@luke-hill I'm seeing lots of stuff around deprecations in the failures.

File: lib/cucumber/rails/action_dispatch.rb (hunk 1 above)
Comment (luke-hill) [reply lib/cucumber/rails/action_dispatch.rb]: It will normally, but because we're doing a large refactor, lets be consistent.

**Comment by luke-hill** [comment]
The failures aren't anything to worry about if they're rails6. They changed something between 6.0.1 and 6.0.2 that we've yet to hear back / diagnose

**Comment by wagenet** [comment]
@luke-hill ok, looks like we're probably ok now.

**Comment by aslakhellesoy** [comment]
Hi @wagenet,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber
